# Generated by Django 4.2.8 on 2023-12-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0037_historicallinkuser_is_superuser_linkuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallink',
            name='folder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='perma.folder'),
        ),
        migrations.AddField(
            model_name='link',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='perma_links', to='perma.folder'),
        ),
    ]
