# Generated by Django 4.2.8 on 2023-12-13 15:38

from django.db import migrations
from django.db.models import OuterRef, Subquery

def backfill_folder_id(apps, schema_editor):
    Link = apps.get_model('perma', 'Link')
    LinkFolder = Link.folders.through

    Link.objects.update(
        folder_id=Subquery(
            LinkFolder.objects.filter(
                link_id=OuterRef('guid')
            ).values_list('folder_id', flat=True)[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0038_historicallink_folder_link_folder'),
    ]

    operations = [
        migrations.RunPython(backfill_folder_id, migrations.RunPython.noop, elidable=True)
    ]
