# Generated by Django 4.2.8 on 2023-12-13 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0039_auto_20231213_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='folders',
        ),
        migrations.AlterField(
            model_name='link',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='links', to='perma.folder'),
        ),
    ]
