# Generated by Django 2.2.22 on 2021-05-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0067_auto_20210521_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalLink',
        ),
    ]
